services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql:ro
      

